// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.appointments_status */
export type AppointmentsStatusId = number & { __brand: 'AppointmentsStatusId' };

/** Represents the table public.appointments_status */
export default interface AppointmentsStatusTable {
  id: ColumnType<AppointmentsStatusId, AppointmentsStatusId | undefined, AppointmentsStatusId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  color: ColumnType<string, string, string>;
}

export type AppointmentsStatus = Selectable<AppointmentsStatusTable>;

export type NewAppointmentsStatus = Insertable<AppointmentsStatusTable>;

export type AppointmentsStatusUpdate = Updateable<AppointmentsStatusTable>;
