// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.appointments */
export type AppointmentsId = number & { __brand: 'AppointmentsId' };

/** Represents the table public.appointments */
export default interface AppointmentsTable {
  id: ColumnType<AppointmentsId, AppointmentsId | undefined, AppointmentsId>;

  userId: ColumnType<number | null, number | null, number | null>;

  barberId: ColumnType<number | null, number | null, number | null>;

  startTime: ColumnType<Date, Date | string, Date | string>;

  endTime: ColumnType<Date, Date | string, Date | string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  serviceId: ColumnType<number | null, number | null, number | null>;

  paymentMethod: ColumnType<string | null, string | null, string | null>;

  statusId: ColumnType<number | null, number | null, number | null>;
}

export type Appointments = Selectable<AppointmentsTable>;

export type NewAppointments = Insertable<AppointmentsTable>;

export type AppointmentsUpdate = Updateable<AppointmentsTable>;
