// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.email_verifications */
export type EmailVerificationsId = number & { __brand: 'EmailVerificationsId' };

/** Represents the table public.email_verifications */
export default interface EmailVerificationsTable {
  id: ColumnType<EmailVerificationsId, EmailVerificationsId | undefined, EmailVerificationsId>;

  email: ColumnType<string, string, string>;

  code: ColumnType<string, string, string>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  expirationAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type EmailVerifications = Selectable<EmailVerificationsTable>;

export type NewEmailVerifications = Insertable<EmailVerificationsTable>;

export type EmailVerificationsUpdate = Updateable<EmailVerificationsTable>;
