// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.payments_status */
export type PaymentsStatusId = number & { __brand: 'PaymentsStatusId' };

/** Represents the table public.payments_status */
export default interface PaymentsStatusTable {
  id: ColumnType<PaymentsStatusId, PaymentsStatusId | undefined, PaymentsStatusId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  color: ColumnType<string, string, string>;
}

export type PaymentsStatus = Selectable<PaymentsStatusTable>;

export type NewPaymentsStatus = Insertable<PaymentsStatusTable>;

export type PaymentsStatusUpdate = Updateable<PaymentsStatusTable>;
