// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.payment_methods */
export type PaymentMethodsId = number & { __brand: 'PaymentMethodsId' };

/** Represents the table public.payment_methods */
export default interface PaymentMethodsTable {
  id: ColumnType<PaymentMethodsId, PaymentMethodsId | undefined, PaymentMethodsId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;
}

export type PaymentMethods = Selectable<PaymentMethodsTable>;

export type NewPaymentMethods = Insertable<PaymentMethodsTable>;

export type PaymentMethodsUpdate = Updateable<PaymentMethodsTable>;
