// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PaymentsStatusId } from './PaymentsStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.payments */
export type PaymentsId = number & { __brand: 'PaymentsId' };

/** Represents the table public.payments */
export default interface PaymentsTable {
  id: ColumnType<PaymentsId, PaymentsId | undefined, PaymentsId>;

  appointmentId: ColumnType<number | null, number | null, number | null>;

  amount: ColumnType<string, string, string>;

  paymentDate: ColumnType<Date, Date | string, Date | string>;

  receiptUrl: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  paymentStatus: ColumnType<number | null, number | null, number | null>;

  paymentMethodsId: ColumnType<number | null, number | null, number | null>;

  paymentStatusId: ColumnType<PaymentsStatusId | null, PaymentsStatusId | null, PaymentsStatusId | null>;
}

export type Payments = Selectable<PaymentsTable>;

export type NewPayments = Insertable<PaymentsTable>;

export type PaymentsUpdate = Updateable<PaymentsTable>;
