// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = number & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, UsersId | undefined, UsersId>;

  username: ColumnType<string, string, string>;

  email: ColumnType<string, string, string>;

  password: ColumnType<string, string, string>;

  photo: ColumnType<string | null, string | null, string | null>;

  phoneNumber: ColumnType<string | null, string | null, string | null>;

  cpf: ColumnType<string | null, string | null, string | null>;

  address: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updatedAt: ColumnType<Date | null, Date | string | null, Date | string | null>;

  lastLogin: ColumnType<Date | null, Date | string | null, Date | string | null>;

  isActive: ColumnType<boolean | null, boolean | null, boolean | null>;

  isAccountActive: ColumnType<boolean, boolean | undefined, boolean>;

  roles: ColumnType<string[] | null, string[] | null, string[] | null>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
